version: '2'
services:
  db:
    image: library/mysql:5.5.47
    environment:
      MYSQL_ROOT_PASSWORD: wasenhorn
    ports:
      - "3306:3306"
    env_file: 
      - '.env.db'
  web:
    build: .
    command: bash -c ". ./setup.sh && rails s puma -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/escapeApp
    ports:
      - "3000:3000"
    links: 
      - db
    env_file:
      - '.env.web'